### PR TITLE
filetranspile: Support v2 and v3 specs for files

### PR DESCRIPTION
**Pull request by ashcrow**
See https://github.com/coreos/ignition/blob/master/doc/configuration-v3_0.md

### CODE REVIEW

**Comment by ashcrow** [comment]
Rebased on master.

**Comment by dustymabe** [comment]
this seems to work OK for me and removes some warnings I was getting from ignition-validate because of spec v3 changes.

**Comment by ashcrow** [comment]
Thank you @dustymabe!

**Review by dustymabe — APPROVED** [review]
Let's merge this

**Comment by dustymabe** [comment]
> Let's merge this

wow haha - my browser page hadn't refreshed

**Pull request merged**
