### PR TITLE
filetranspile: Support base64 encoded file contents

### LINKED ISSUE #20: base64 encoded output
A command line switch to have base64 encoded utf-8 output would be perfect!
Me python skills are very limited ... i tried to modify your code but the result looks not as expected ... :(

### PR DESCRIPTION
**Pull request by ashcrow**
Content is now base64 encoded and includes sensed mime type.

```    
$ ./filetranspile -p -f test/fakeroot/    
{
  "ignition": {
    "version": "2.3.0"
  },
  "storage": {
    "files": [
      {
        "contents": {
          "source": "data:text/plain;charset=us-ascii;base64,c29tZXRoaW5nCg=="
        },
        "filesystem": "root",
        "mode": 384,
        "path": "/etc/hostname"
      },
[...]
```    

PTAL @lbohnsac and let me know if this works as you'd expect. If so I'll follow up with a doc update as well.

Closes #20

### CODE REVIEW

**Comment by dustymabe** [comment]
Is there a way we can not make a new option for this? I'd prefer one of:

- base64 encode everything by default
- detect the type of file and base64 binary files

**Comment by ashcrow** [comment]
> Is there a way we can not make a new option for this? I'd prefer one of:
> 
>     * base64 encode everything by default
>     * detect the type of file and base64 binary files

Yes, and the above two are doable :+1:

**Comment by ashcrow** [comment]
Updated to base64 encoding always and sense the mimetype using `magic`.

**Review by dustymabe — APPROVED** [review]
LGTM. tested locally on a few files. Didn't test with any binaries though.

**Comment by ashcrow** [comment]
Awesome, thank you @dustymabe!!

@lbohnsac would you mind giving it a go with a binary? If all is well I'll update the docs as well and merge this.

**Comment by ashcrow** [comment]
Per discussion with @dustymabe we'll merge as is and fix bugs if they occur.

**Pull request merged**
