### PR TITLE
Overwrite if a file path already exists.

### LINKED ISSUE #28: File transpiler does not replace the file if it already exists in ignition.
If a ".storage.file" with the same `path` is already existed in ignition config, it does not replace it, but rather creates a new block which cause duplication error.

### PR DESCRIPTION
**Pull request by m-yosefpor**
Fixes https://github.com/ashcrow/filetranspiler/issues/28

This is tested.

### CODE REVIEW

**Comment by ashcrow** [comment]
Thank you @m-yosefpor! I added a test in https://github.com/ashcrow/filetranspiler/pull/30 so the functionality doesn't accidentally regress. PTAL and give it a shot and ensure that the results are what you expect. If so I'm happy to merge :smile:.

**Comment by m-yosefpor** [comment]
Sure @ashcrow. Thanks.

**Review by ashcrow — APPROVED** [review]
Fantastic work! This looks good to me!

**Comment by ashcrow** [comment]
I've tested with the internal ignition data url parser and things seem great. Doing a little extra testing with some VMs with the output before I merge.

**Comment by ashcrow** [comment]
Passing the resulting ignition worked in VMs!

**Pull request merged**
